# Generated by Django 2.2 on 2019-04-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissionnews', '0001_initial'),
        ('eventcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admissionnews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admissionnews.AdmissionNews'),
            preserve_default=False,
        ),
    ]
