# Generated by Django 2.2 on 2019-04-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0002_event_admissionnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admissionnews',
        ),
    ]
