# Generated by Django 2.2 on 2019-04-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissionnews', '0002_auto_20190420_0502'),
        ('eventcalendar', '0003_remove_event_admissionnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admissionnews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admissionnews.AdmissionNews'),
            preserve_default=False,
        ),
    ]
