# Generated by Django 2.2 on 2019-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionnews', '0002_auto_20190417_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
